### ISSUE TITLE
Client::partitions finds partitions from wrong tables

### ISSUE THREAD

**Issue by astax-t** [smi2/phpClickHouse#187]
Is there any reason why \ClickHouseDB\Client::partitions uses this query 
`WHERE like(table,'%$table%') AND database='$database'$whereActiveClause`
and not
`WHERE table='$table' AND database='$database'$whereActiveClause` ?

Looking for substring doesn't seem to be correct - this finds partitions not only from the requested table.

**Comment by isublimity** [comment]
Yes, this is a mistake, I corrected it in dev23 - I will publish it in the master soon

**Comment by amw863** [comment]
Hi, i get a bug when is use tags: 1.5.1. 

My PHP version is 7.1

 I find the reason is below：https://www.php.net/manual/en/language.types.string.php

Prior to PHP 7.3.0, it is very important to note that the line with the closing identifier must contain no other characters, except a semicolon (;). That means especially that the identifier may not be indented, and there may not be any spaces or tabs before or after the semicolon. It's also important to realize that the first character before the closing identifier must be a newline as defined by the local operating system. This is \n on UNIX systems, including macOS. The closing delimiter must also be followed by a newline.

Or you can solve this problem more elegantly without upgrading the PHP version
